repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: .venv/Scripts/python.exe -m ruff check src tests scripts --fix
        language: system
        pass_filenames: false
