[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "benchcaddy"
version = "0.1.4"
description = "Lightweight benchmark sweeps with environment capture and CLI."
readme = "README.md"
requires-python = ">=3.10"
keywords = ["benchmark", "performance", "profiling", "cli", "testing"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Testing",
    "Topic :: System :: Benchmark",
]

authors = [
  {name = "Matthias Lenga" }
]

license = "Apache-2.0"
license-files = ["LICENSE"]

dependencies = [
    "sqlalchemy>=2.0.41",
    "typer>=0.12.5",
    "rich>=13.9.4",
    "gitpython>=3.1.43",
    "psutil>=6.1.1",
    "numpy>=2.2.6",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3",
    "ruff>=0.11.11",
    "pre-commit>=4.2",
    "pylint>=3.3.7",
    "vulture>=2.14",
    "radon>=6.0.1",
]

[project.urls]
Homepage = "https://github.com/MatthiasLen/BenchCaddy"
Repository = "https://github.com/MatthiasLen/BenchCaddy"
Issues = "https://github.com/MatthiasLen/BenchCaddy/issues"

[project.scripts]
benchcaddy = "benchcaddy.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 180
target-version = "py310"
extend-exclude = [".venv", "build", "dist"]

[tool.ruff.lint]
select = [
    "E",    # Pycodestyle errors
    "F",    # Pyflakes (Logic bugs)
    "I",    # Isort (Organize imports automatically)
    "UP",   # Pyupgrade (Force modern Python syntax)
    "B",    # Bugbear (Finds common design flaws)
    "SIM",  # Simplify (Tells the AI to write simpler code)
]
ignore = ["E701"] # "E702"

[tool.ruff.format]
skip-magic-trailing-comma = false
